[project]
name = "delaunay-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.8.0",
    "jupyter>=1.1.1",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
]
